// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipdiwguzirjcnaqtzppi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZGl3Z3V6aXJqY25hcXR6cHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxNDMxMjgsImV4cCI6MjA5OTcxOTEyOH0.5qv57fTp8NkdyYyDlPbqwbjGcjfUpxFEZ1CL2vzl15Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});